# Generated by Django 4.2 on 2023-05-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_employee',
        ),
    ]
