# Generated by Django 4.2 on 2023-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_delete_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_gender', models.CharField(max_length=50)),
                ('employee_dept', models.CharField(max_length=50)),
                ('employee_salary', models.CharField(max_length=50)),
            ],
        ),
    ]
