# Generated by Django 4.2 on 2023-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=50)),
                ('Admin_contact', models.CharField(max_length=50)),
                ('Admin_email', models.CharField(max_length=50)),
                ('Admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
