# Generated by Django 4.2 on 2023-06-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=50)),
            ],
        ),
    ]
