# Generated by Django 4.2 on 2023-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_delete_tbl_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newuser_name', models.CharField(max_length=50)),
                ('newuser_contact', models.CharField(max_length=50)),
                ('newuser_email', models.CharField(max_length=50)),
                ('newuser_address', models.CharField(max_length=50)),
                ('newuser_photo', models.FileField(upload_to='')),
                ('newuser_proof', models.FileField(upload_to='')),
                ('newuser_password', models.CharField(max_length=50)),
                ('newuser_confirmpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
