# Generated by Django 4.2 on 2023-06-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_itemcode', models.CharField(max_length=50)),
                ('item_itemname', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=50)),
                ('item_description', models.CharField(max_length=50)),
                ('item_image', models.FileField(upload_to='')),
            ],
        ),
    ]
