# Generated by Django 4.2 on 2023-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_item',
            name='item_image',
            field=models.FileField(upload_to='item_imgs/'),
        ),
    ]
