# Generated by Django 4.2 on 2023-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_alter_tbl_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_newuser',
            name='newuser_photo',
            field=models.FileField(upload_to='newuser_imgs/'),
        ),
        migrations.AlterField(
            model_name='tbl_newuser',
            name='newuser_proof',
            field=models.FileField(upload_to='newuser_imgs/'),
        ),
    ]
