# Generated by Django 4.2 on 2023-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_alter_tbl_newuser_newuser_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_newuser',
            name='newuser_confirmpassword',
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='product_image',
            field=models.FileField(null=True, upload_to='product_imgs/'),
        ),
    ]
