# Generated by Django 4.2 on 2023-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_Email', models.CharField(max_length=50)),
                ('login_password', models.CharField(max_length=50)),
            ],
        ),
    ]
