# Generated by Django 4.2 on 2023-07-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_login',
        ),
    ]
