# Generated by Django 4.2 on 2024-02-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newuser',
        ),
    ]
